workflow changes

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -8,8 +8,19 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
-      - name: Run RuffFix
-        uses: YuheshPandian/RuffFix@v1.2.0
+      - uses: actions/checkout@v4 # Note: v4 is the current standard
+      - name: Set up Python
+        uses: actions/setup-python@v5
         with:
-          mode: all
+          python-version: "3.x"
+      - name: Install the code linting and formatting tool Ruff
+        run: pipx install ruff
+
+      - name: Lint code with Ruff
+        run: ruff check --output-format=github --target-version=py39
+        # If this fails, the job is marked as "Failed", but...
+
+      - name: Check code formatting with Ruff
+        # ...this line ensures this step runs anyway!
+        if: success() || failure()
+        run: ruff format --diff --target-version=py39
